services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: certificator-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    networks:
      - certificator-network

networks:
  certificator-network:
    driver: bridge
