import { CertificateElement } from '@/types/CertificateTemplate';

export type LayoutCategory = 'digital' | 'minimal' | 'modern';
export type LayoutOrientation = 'portrait' | 'landscape';

export interface SystemLayoutPreset {
  id: string;
  name: string;
  description: string;
  category: LayoutCategory;
  orientation: LayoutOrientation;
  variables: string[];
  elements: CertificateElement[];
}

const createText = (
  id: string,
  label: string,
  content: string,
  x: number,
  y: number,
  width: number,
  height: number,
  fontSize: number,
  color = '#111827',
  fontWeight: 'normal' | 'bold' | '500' | '600' | '700' = 'normal',
  textAlign: 'left' | 'center' | 'right' = 'left'
): CertificateElement => ({
  id,
  type: 'text',
  label,
  x,
  y,
  width,
  height,
  rotation: 0,
  zIndex: 1,
  visible: true,
  content,
  fontSize,
  fontFamily: 'Arial',
  fontWeight,
  color,
  textAlign,
  lineHeight: 1.3,
});

const createBoundary = (id: string, borderColor: string, borderWidth = 2): CertificateElement => ({
  id,
  type: 'shape',
  label: 'System Boundary',
  x: 2.5,
  y: 2.5,
  width: 95,
  height: 95,
  rotation: 0,
  zIndex: 0,
  visible: true,
  shapeType: 'rectangle',
  backgroundColor: 'transparent',
  borderColor,
  borderWidth,
});

export const systemLayoutPresets: SystemLayoutPreset[] = [
  {
    id: 'digital-blue-landscape',
    name: 'Digital Blue',
    description: 'Professional landscape template with blue accents.',
    category: 'digital',
    orientation: 'landscape',
    variables: ['[recipient.name]', '[certificate.issued_on]', '[certificate.uuid]'],
    elements: [
      createBoundary('system-boundary-db-l', '#1e3a8a', 3),
      createText('db-l-title', 'Title', 'CERTIFICATE OF COMPLETION', 10, 10, 65, 10, 44, '#1e3a8a', 'bold'),
      createText('db-l-subtitle', 'Subtitle', 'COMMUNICATION SKILLS COURSE', 10, 20, 60, 6, 18, '#1f3b64', '600'),
      createText('db-l-awarded', 'Awarded', 'AWARDED TO', 10, 34, 30, 4, 12, '#4b5563', '600'),
      createText('db-l-name', 'Recipient', '[recipient.name]', 10, 39, 65, 10, 30, '#0f2d50', 'bold'),
      createText('db-l-body', 'Body', 'HAS MERITORIOUSLY COMPLETED THE PROGRAM SUCCESSFULLY', 10, 52, 70, 7, 14, '#1f3b64', '600'),
      createText('db-l-date', 'Date', '[certificate.issued_on]', 10, 88, 25, 4, 12, '#1f3b64', '600'),
      createText('db-l-id', 'Id', '[certificate.uuid]', 76, 88, 18, 4, 11, '#1f3b64', '600', 'right'),
    ],
  },
  {
    id: 'digital-green-landscape',
    name: 'Digital Green',
    description: 'Data-rich modern certificate with green side panel.',
    category: 'digital',
    orientation: 'landscape',
    variables: ['[recipient.name]', '[certificate.issued_on]', '[certificate.uuid]'],
    elements: [
      createBoundary('system-boundary-dg-l', '#36512a', 3),
      {
        id: 'dg-side',
        type: 'shape',
        label: 'Side Accent',
        x: 80,
        y: 2.5,
        width: 15,
        height: 95,
        rotation: 0,
        zIndex: 1,
        visible: true,
        shapeType: 'rectangle',
        backgroundColor: '#36512a',
        borderColor: '#36512a',
        borderWidth: 0,
      },
      createText('dg-title', 'Title', 'CERTIFICATE OF COMPLETION', 8, 10, 60, 14, 28, '#36512a', 'bold'),
      createText('dg-sub', 'Subtitle', 'Proudly presented to', 8, 30, 30, 5, 14, '#4b5563'),
      createText('dg-name', 'Recipient', '[recipient.name]', 8, 37, 58, 9, 28, '#36512a', 'bold'),
      createText('dg-course', 'Course', 'ADVANCED COURSE STRATEGIES', 8, 55, 70, 8, 20, '#36512a', 'bold'),
      createText('dg-hours', 'Hours', 'Hours: 48', 8, 66, 30, 5, 13, '#1f2937', '600'),
      createText('dg-points', 'Points', 'Points: 975', 42, 66, 30, 5, 13, '#1f2937', '600'),
      createText('dg-date', 'Date', '[certificate.issued_on]', 82, 10, 11, 8, 10, '#f8fafc', '600', 'center'),
      createText('dg-id', 'Id', '[certificate.uuid]', 82, 22, 11, 5, 10, '#f8fafc', '600', 'center'),
    ],
  },
  {
    id: 'minimal-clean-portrait',
    name: 'Minimal Clean',
    description: 'Simple and elegant portrait certificate.',
    category: 'minimal',
    orientation: 'portrait',
    variables: ['[recipient.name]', '[certificate.issued_on]', '[certificate.uuid]'],
    elements: [
      createBoundary('system-boundary-mc-p', '#9ca3af', 1),
      createText('mc-title', 'Title', 'YOUR CERTIFICATE', 20, 14, 60, 10, 34, '#3f3f46', '600', 'center'),
      createText('mc-sub', 'Subtitle', 'OF ACHIEVEMENT', 30, 22, 40, 6, 20, '#52525b', '500', 'center'),
      createText('mc-label', 'Label', 'Proudly presented to:', 34, 39, 32, 4, 11, '#737373', '500', 'center'),
      createText('mc-name', 'Recipient', '[recipient.name]', 25, 44, 50, 9, 28, '#3f3f46', '600', 'center'),
      createText('mc-body', 'Body', 'for outstanding completion of the training program', 20, 57, 60, 7, 12, '#52525b', '500', 'center'),
      createText('mc-id-label', 'Id Label', 'Certificate ID', 20, 83, 18, 4, 10, '#52525b', '500', 'center'),
      createText('mc-id', 'Id', '[certificate.uuid]', 18, 88, 24, 4, 10, '#52525b', '600', 'center'),
      createText('mc-date-label', 'Date Label', 'Issue Date', 62, 83, 18, 4, 10, '#52525b', '500', 'center'),
      createText('mc-date', 'Date', '[certificate.issued_on]', 58, 88, 24, 4, 10, '#52525b', '600', 'center'),
    ],
  },
  {
    id: 'minimal-mono-landscape',
    name: 'Minimal Mono',
    description: 'Black-and-white appreciation style template.',
    category: 'minimal',
    orientation: 'landscape',
    variables: ['[recipient.name]', '[certificate.issued_on]'],
    elements: [
      createBoundary('system-boundary-mm-l', '#27272a', 2),
      {
        id: 'mm-header',
        type: 'shape',
        label: 'Header Block',
        x: 2.5,
        y: 2.5,
        width: 95,
        height: 28,
        rotation: 0,
        zIndex: 1,
        visible: true,
        shapeType: 'rectangle',
        backgroundColor: '#09090b',
        borderColor: '#09090b',
        borderWidth: 0,
      },
      createText('mm-title', 'Title', 'CERTIFICATE OF APPRECIATION', 8, 10, 55, 12, 28, '#f8fafc', 'bold'),
      createText('mm-name', 'Name', '[recipient.name]', 8, 45, 44, 9, 26, '#111827', '600'),
      createText('mm-body', 'Body', 'In recognition of valuable contributions and professional excellence.', 8, 57, 58, 8, 13, '#111827', '500'),
      createText('mm-date', 'Date', '[certificate.issued_on]', 78, 76, 16, 5, 12, '#111827', '600', 'right'),
    ],
  },
  {
    id: 'modern-navy-landscape',
    name: 'Modern Navy',
    description: 'Corporate style template with side panel.',
    category: 'modern',
    orientation: 'landscape',
    variables: ['[recipient.name]', '[certificate.issued_on]', '[certificate.uuid]'],
    elements: [
      createBoundary('system-boundary-mn-l', '#1e3a8a', 3),
      {
        id: 'mn-left',
        type: 'shape',
        label: 'Left Panel',
        x: 2.5,
        y: 2.5,
        width: 18,
        height: 95,
        rotation: 0,
        zIndex: 1,
        visible: true,
        shapeType: 'rectangle',
        backgroundColor: '#1e3a8a',
        borderColor: '#1e3a8a',
        borderWidth: 0,
      },
      createText('mn-title', 'Title', 'CERTIFICATE OF ATTENDANCE', 28, 10, 56, 12, 34, '#2459a4', 'bold'),
      createText('mn-sub', 'Subtitle', 'PROUDLY PRESENTED TO', 28, 30, 30, 5, 12, '#1e3a8a', 'bold'),
      createText('mn-name', 'Recipient', '[recipient.name]', 28, 36, 56, 9, 30, '#2459a4', 'bold'),
      createText('mn-body', 'Body', 'For attending the advanced professional masterclass program.', 28, 50, 56, 8, 13, '#64748b', '600'),
      createText('mn-date', 'Date', '[certificate.issued_on]', 41, 77, 18, 5, 12, '#64748b', '600', 'center'),
      createText('mn-id', 'ID', '[certificate.uuid]', 8, 89, 10, 4, 10, '#f8fafc', '600', 'center'),
    ],
  },
  {
    id: 'modern-accent-portrait',
    name: 'Modern Accent',
    description: 'Portrait layout with bold header and signature section.',
    category: 'modern',
    orientation: 'portrait',
    variables: ['[recipient.name]', '[certificate.issued_on]'],
    elements: [
      createBoundary('system-boundary-ma-p', '#0f172a', 2),
      {
        id: 'ma-top',
        type: 'shape',
        label: 'Top Bar',
        x: 2.5,
        y: 10,
        width: 95,
        height: 11,
        rotation: 0,
        zIndex: 1,
        visible: true,
        shapeType: 'rectangle',
        backgroundColor: '#0f172a',
        borderColor: '#0f172a',
        borderWidth: 0,
      },
      createText('ma-title', 'Title', 'CERTIFICATE OF APPRECIATION', 10, 12, 78, 8, 32, '#f8fafc', 'bold', 'center'),
      createText('ma-name', 'Name', '[recipient.name]', 18, 43, 64, 10, 36, '#3f3f46', 'bold', 'center'),
      createText('ma-body', 'Body', 'For exceptional contribution and commitment to excellence.', 16, 58, 68, 8, 14, '#71717a', '500', 'center'),
      createText('ma-date', 'Date', '[certificate.issued_on]', 40, 87, 20, 5, 12, '#52525b', '600', 'center'),
    ],
  },
];
