import { CertificateElement } from '@/types/CertificateTemplate';

export type LayoutCategory = 'digital' | 'minimal' | 'modern';
export type LayoutOrientation = 'portrait' | 'landscape';

export interface SystemLayoutPreset {
  id: string;
  name: string;
  description: string;
  category: LayoutCategory;
  orientation: LayoutOrientation;
  variables: string[];
  elements: CertificateElement[];
}

const createText = (
  id: string,
  label: string,
  content: string,
  x: number,
  y: number,
  width: number,
  height: number,
  fontSize: number,
  color = '#111827',
  fontWeight: 'normal' | 'bold' | '500' | '600' | '700' = 'normal',
  textAlign: 'left' | 'center' | 'right' = 'left'
): CertificateElement => ({
  id,
  type: 'text',
  label,
  x,
  y,
  width,
  height,
  rotation: 0,
  zIndex: 1,
  visible: true,
  content,
  fontSize,
  fontFamily: 'Arial',
  fontWeight,
  color,
  textAlign,
  lineHeight: 1.3,
});

const createBoundary = (id: string, borderColor: string, borderWidth = 2): CertificateElement => ({
  id,
  type: 'shape',
  label: 'System Boundary',
  x: 2.5,
  y: 2.5,
  width: 94.5,
  height: 94.5,
  rotation: 0,
  zIndex: 0,
  visible: true,
  shapeType: 'rectangle',
  backgroundColor: 'transparent',
  borderColor,
  borderWidth,
});

export const systemLayoutPresets: SystemLayoutPreset[] = [
  {
    id: 'digital-blue-landscape',
    name: 'Digital Blue',
    description: 'Professional landscape template with blue accents.',
    category: 'digital',
    orientation: 'landscape',
    variables: ['[recipient.name]', '[certificate.issued_on]', '[certificate.uuid]'],
    elements: [
      createBoundary('system-boundary-db-l', '#1e3a8a', 3),
      createText('db-l-title', 'Title', 'CERTIFICATE OF COMPLETION', 10, 10, 65, 10, 44, '#1e3a8a', 'bold'),
      createText('db-l-subtitle', 'Subtitle', 'COMMUNICATION SKILLS COURSE', 10, 20, 60, 6, 18, '#1f3b64', '600'),
      createText('db-l-awarded', 'Awarded', 'AWARDED TO', 10, 34, 30, 4, 12, '#4b5563', '600'),
      createText('db-l-name', 'Recipient', '[recipient.name]', 10, 39, 65, 10, 30, '#0f2d50', 'bold'),
      createText('db-l-body', 'Body', 'HAS MERITORIOUSLY COMPLETED THE PROGRAM SUCCESSFULLY', 10, 52, 70, 7, 14, '#1f3b64', '600'),
      createText('db-l-date', 'Date', '[certificate.issued_on]', 10, 88, 25, 4, 12, '#1f3b64', '600'),
      createText('db-l-id', 'Id', '[certificate.uuid]', 76, 88, 18, 4, 11, '#1f3b64', '600', 'right'),
    ],
  },
  {
    id: 'digital-green-landscape',
    name: 'Digital Green',
    description: 'Data-rich modern certificate with green side panel.',
    category: 'digital',
    orientation: 'landscape',
    variables: ['[recipient.name]', '[certificate.issued_on]', '[certificate.uuid]'],
    elements: [
      createBoundary('system-boundary-dg-l', '#36512a', 3),
      {
        id: 'dg-side',
        type: 'shape',
        label: 'Side Accent',
        x: 80,
        y: 2.5,
        width: 15,
        height: 95,
        rotation: 0,
        zIndex: 1,
        visible: true,
        shapeType: 'rectangle',
        backgroundColor: '#36512a',
        borderColor: '#36512a',
        borderWidth: 0,
      },
      createText('dg-title', 'Title', 'CERTIFICATE OF COMPLETION', 8, 10, 60, 14, 28, '#36512a', 'bold'),
      createText('dg-sub', 'Subtitle', 'Proudly presented to', 8, 30, 30, 5, 14, '#4b5563'),
      createText('dg-name', 'Recipient', '[recipient.name]', 8, 37, 58, 9, 28, '#36512a', 'bold'),
      createText('dg-course', 'Course', 'ADVANCED COURSE STRATEGIES', 8, 55, 70, 8, 20, '#36512a', 'bold'),
      createText('dg-hours', 'Hours', 'Hours: 48', 8, 66, 30, 5, 13, '#1f2937', '600'),
      createText('dg-points', 'Points', 'Points: 975', 42, 66, 30, 5, 13, '#1f2937', '600'),
      createText('dg-date', 'Date', '[certificate.issued_on]', 82, 10, 11, 8, 10, '#f8fafc', '600', 'center'),
      createText('dg-id', 'Id', '[certificate.uuid]', 82, 22, 11, 5, 10, '#f8fafc', '600', 'center'),
    ],
  },
  {
    id: 'minimal-clean-portrait',
    name: 'Minimal Clean',
    description: 'Simple and elegant portrait certificate.',
    category: 'minimal',
    orientation: 'portrait',
    variables: ['[recipient.name]', '[certificate.issued_on]', '[certificate.uuid]'],
    elements: [
      createBoundary('system-boundary-mc-p', '#9ca3af', 1),
      createText('mc-title', 'Title', 'YOUR CERTIFICATE', 20, 14, 60, 10, 34, '#3f3f46', '600', 'center'),
      createText('mc-sub', 'Subtitle', 'OF ACHIEVEMENT', 30, 22, 40, 6, 20, '#52525b', '500', 'center'),
      createText('mc-label', 'Label', 'Proudly presented to:', 34, 39, 32, 4, 11, '#737373', '500', 'center'),
      createText('mc-name', 'Recipient', '[recipient.name]', 25, 44, 50, 9, 28, '#3f3f46', '600', 'center'),
      createText('mc-body', 'Body', 'for outstanding completion of the training program', 20, 57, 60, 7, 12, '#52525b', '500', 'center'),
      createText('mc-id-label', 'Id Label', 'Certificate ID', 20, 83, 18, 4, 10, '#52525b', '500', 'center'),
      createText('mc-id', 'Id', '[certificate.uuid]', 18, 88, 24, 4, 10, '#52525b', '600', 'center'),
      createText('mc-date-label', 'Date Label', 'Issue Date', 62, 83, 18, 4, 10, '#52525b', '500', 'center'),
      createText('mc-date', 'Date', '[certificate.issued_on]', 58, 88, 24, 4, 10, '#52525b', '600', 'center'),
    ],
  },
  {
    id: 'minimal-mono-landscape',
    name: 'Minimal Mono',
    description: 'Black-and-white appreciation style template.',
    category: 'minimal',
    orientation: 'landscape',
    variables: ['[recipient.name]', '[certificate.issued_on]'],
    elements: [
      createBoundary('system-boundary-mm-l', '#27272a', 2),
      {
        id: 'mm-header',
        type: 'shape',
        label: 'Header Block',
        x: 2.5,
        y: 2.5,
        width: 95,
        height: 28,
        rotation: 0,
        zIndex: 1,
        visible: true,
        shapeType: 'rectangle',
        backgroundColor: '#09090b',
        borderColor: '#09090b',
        borderWidth: 0,
      },
      createText('mm-title', 'Title', 'CERTIFICATE OF APPRECIATION', 8, 10, 55, 12, 28, '#f8fafc', 'bold'),
      createText('mm-name', 'Name', '[recipient.name]', 8, 45, 44, 9, 26, '#111827', '600'),
      createText('mm-body', 'Body', 'In recognition of valuable contributions and professional excellence.', 8, 57, 58, 8, 13, '#111827', '500'),
      createText('mm-date', 'Date', '[certificate.issued_on]', 78, 76, 16, 5, 12, '#111827', '600', 'right'),
    ],
  },
  {
    id: 'modern-navy-landscape',
    name: 'Modern Navy',
    description: 'Corporate style template with side panel.',
    category: 'modern',
    orientation: 'landscape',
    variables: ['[recipient.name]', '[certificate.issued_on]', '[certificate.uuid]'],
    elements: [
      createBoundary('system-boundary-mn-l', '#1e3a8a', 3),
      {
        id: 'mn-left',
        type: 'shape',
        label: 'Left Panel',
        x: 2.5,
        y: 2.5,
        width: 18,
        height: 95,
        rotation: 0,
        zIndex: 1,
        visible: true,
        shapeType: 'rectangle',
        backgroundColor: '#1e3a8a',
        borderColor: '#1e3a8a',
        borderWidth: 0,
      },
      createText('mn-title', 'Title', 'CERTIFICATE OF ATTENDANCE', 28, 10, 56, 12, 34, '#2459a4', 'bold'),
      createText('mn-sub', 'Subtitle', 'PROUDLY PRESENTED TO', 28, 30, 30, 5, 12, '#1e3a8a', 'bold'),
      createText('mn-name', 'Recipient', '[recipient.name]', 28, 36, 56, 9, 30, '#2459a4', 'bold'),
      createText('mn-body', 'Body', 'For attending the advanced professional masterclass program.', 28, 50, 56, 8, 13, '#64748b', '600'),
      createText('mn-date', 'Date', '[certificate.issued_on]', 41, 77, 18, 5, 12, '#64748b', '600', 'center'),
      createText('mn-id', 'ID', '[certificate.uuid]', 8, 89, 10, 4, 10, '#f8fafc', '600', 'center'),
    ],
  },
  {
    id: 'modern-accent-portrait',
    name: 'Modern Accent',
    description: 'Portrait layout with bold header and signature section.',
    category: 'modern',
    orientation: 'portrait',
    variables: ['[recipient.name]', '[certificate.issued_on]'],
    elements: [
      createBoundary('system-boundary-ma-p', '#0f172a', 2),
      {
        id: 'ma-top',
        type: 'shape',
        label: 'Top Bar',
        x: 2.5,
        y: 10,
        width: 95,
        height: 11,
        rotation: 0,
        zIndex: 1,
        visible: true,
        shapeType: 'rectangle',
        backgroundColor: '#0f172a',
        borderColor: '#0f172a',
        borderWidth: 0,
      },
      createText('ma-title', 'Title', 'CERTIFICATE OF APPRECIATION', 10, 12, 78, 8, 32, '#f8fafc', 'bold', 'center'),
      createText('ma-name', 'Name', '[recipient.name]', 18, 43, 64, 10, 36, '#3f3f46', 'bold', 'center'),
      createText('ma-body', 'Body', 'For exceptional contribution and commitment to excellence.', 16, 58, 68, 8, 14, '#71717a', '500', 'center'),
      createText('ma-date', 'Date', '[certificate.issued_on]', 40, 87, 20, 5, 12, '#52525b', '600', 'center'),
    ],
  },
  {
    id: 'digital-emerald-portrait',
    name: 'Digital Emerald',
    description: 'Portrait digital certificate with modern score bands.',
    category: 'digital',
    orientation: 'portrait',
    variables: ['[recipient.name]', '[certificate.issued_on]', '[certificate.uuid]'],
    elements: [
      createBoundary('system-boundary-de-p', '#2f5130', 2),
      createText('de-title', 'Title', 'TRAINING COURSE CERTIFICATE', 10, 14, 80, 9, 30, '#312e2e', 'bold', 'center'),
      createText('de-sub', 'Subtitle', 'IS PROUDLY PRESENTED TO', 27, 25, 46, 4, 12, '#737373', '600', 'center'),
      createText('de-name', 'Name', '[recipient.name]', 18, 31, 64, 8, 30, '#3f3f46', '600', 'center'),
      createText('de-course', 'Course', 'HAS SUCCESSFULLY COMPLETED THE ADVANCED COURSE', 14, 43, 72, 7, 13, '#3f3f46', 'bold', 'center'),
      {
        id: 'de-band-1',
        type: 'shape',
        label: 'Score Band 1',
        x: 24,
        y: 56,
        width: 52,
        height: 6,
        rotation: 0,
        zIndex: 1,
        visible: true,
        shapeType: 'rectangle',
        backgroundColor: '#3f7f35',
        borderColor: '#3f7f35',
        borderWidth: 0,
      },
      createText('de-band-1-text', 'Band Text 1', 'RANKING IN THE TOP 5% OF THE CLASS', 24, 57, 52, 4, 10, '#f8fafc', 'bold', 'center'),
      {
        id: 'de-band-2',
        type: 'shape',
        label: 'Score Band 2',
        x: 31,
        y: 64,
        width: 38,
        height: 5,
        rotation: 0,
        zIndex: 1,
        visible: true,
        shapeType: 'rectangle',
        backgroundColor: '#95c98b',
        borderColor: '#95c98b',
        borderWidth: 0,
      },
      createText('de-band-2-text', 'Band Text 2', 'TOTAL SCORE: 99 POINTS', 31, 65, 38, 3, 10, '#f8fafc', 'bold', 'center'),
      createText('de-date', 'Date', '[certificate.issued_on]', 40, 91, 20, 4, 11, '#4b5563', '600', 'center'),
    ],
  },
  {
    id: 'digital-badge-landscape',
    name: 'Digital Badge',
    description: 'Landscape template with right badge and metrics.',
    category: 'digital',
    orientation: 'landscape',
    variables: ['[recipient.name]', '[certificate.issued_on]', '[certificate.uuid]'],
    elements: [
      createBoundary('system-boundary-db2-l', '#1e3a8a', 3),
      {
        id: 'db2-right-panel',
        type: 'shape',
        label: 'Right Panel',
        x: 77,
        y: 2.5,
        width: 15,
        height: 95,
        rotation: 0,
        zIndex: 1,
        visible: true,
        shapeType: 'rectangle',
        backgroundColor: '#0f2a7a',
        borderColor: '#0f2a7a',
        borderWidth: 0,
      },
      createText('db2-title', 'Title', 'Certificate of Completion', 8, 14, 62, 9, 28, '#303038', '600'),
      createText('db2-sub', 'Subtitle', 'This is to certify that', 8, 27, 30, 5, 12, '#4b5563', '500'),
      createText('db2-name', 'Name', '[recipient.name]', 8, 34, 62, 10, 30, '#303038', '600'),
      createText('db2-body', 'Body', 'has successfully completed the leadership program', 8, 49, 62, 8, 13, '#374151', '500'),
      createText('db2-m1', 'Metric 1', '45 PD Credits', 8, 66, 18, 5, 11, '#4b5563', '600', 'center'),
      createText('db2-m2', 'Metric 2', '12 PD Points', 28, 66, 18, 5, 11, '#4b5563', '600', 'center'),
      createText('db2-m3', 'Metric 3', '24 PD Hours', 48, 66, 18, 5, 11, '#4b5563', '600', 'center'),
      createText('db2-date', 'Date', '[certificate.issued_on]', 62, 66, 14, 5, 11, '#4b5563', '600', 'center'),
      createText('db2-id', 'ID', '[certificate.uuid]', 80, 84, 10, 4, 10, '#f8fafc', '600', 'center'),
    ],
  },
  {
    id: 'minimal-center-landscape',
    name: 'Minimal Center',
    description: 'Center-focused clean landscape design.',
    category: 'minimal',
    orientation: 'landscape',
    variables: ['[recipient.name]', '[certificate.issued_on]', '[certificate.uuid]'],
    elements: [
      createBoundary('system-boundary-mc2-l', '#a1a1aa', 1),
      createText('mc2-title', 'Title', 'YOUR CERTIFICATE', 24, 14, 52, 10, 28, '#3f3f46', '600', 'center'),
      createText('mc2-subtitle', 'Subtitle', 'OF ACHIEVEMENT', 32, 23, 36, 6, 18, '#52525b', '500', 'center'),
      createText('mc2-label', 'Label', 'Proudly presented to', 37, 40, 26, 4, 12, '#71717a', '500', 'center'),
      createText('mc2-name', 'Name', '[recipient.name]', 28, 45, 44, 9, 28, '#3f3f46', '600', 'center'),
      createText('mc2-body', 'Body', 'For excellence, dedication, and outstanding performance.', 24, 59, 52, 7, 12, '#52525b', '500', 'center'),
      createText('mc2-id', 'Id', '[certificate.uuid]', 8, 88, 22, 4, 10, '#52525b', '600'),
      createText('mc2-date', 'Date', '[certificate.issued_on]', 70, 88, 22, 4, 10, '#52525b', '600', 'right'),
    ],
  },
  {
    id: 'modern-ribbon-landscape',
    name: 'Modern Ribbon',
    description: 'Bold modern ribbon with strong visual hierarchy.',
    category: 'modern',
    orientation: 'landscape',
    variables: ['[recipient.name]', '[certificate.issued_on]', '[certificate.uuid]'],
    elements: [
      createBoundary('system-boundary-mr-l', '#7f1d1d', 2),
      {
        id: 'mr-ribbon',
        type: 'shape',
        label: 'Ribbon',
        x: 80,
        y: 2.5,
        width: 10,
        height: 26,
        rotation: 0,
        zIndex: 1,
        visible: true,
        shapeType: 'rectangle',
        backgroundColor: '#7f1d1d',
        borderColor: '#7f1d1d',
        borderWidth: 0,
      },
      createText('mr-title', 'Title', 'COURSE CERTIFICATE', 8, 10, 60, 10, 30, '#7f1d1d', '600'),
      createText('mr-sub', 'Subtitle', 'Is proudly conferred upon', 8, 24, 36, 5, 12, '#7f1d1d', '500'),
      createText('mr-name', 'Name', '[recipient.name]', 8, 31, 62, 10, 34, '#7f1d1d', '600'),
      createText('mr-body', 'Body', 'For outstanding performance in the AI learning program.', 8, 47, 60, 10, 14, '#7f1d1d', '500'),
      createText('mr-lessons', 'Lessons', '14/14 Completed Lessons', 8, 64, 18, 8, 11, '#7f1d1d', '600'),
      createText('mr-id', 'Id', '[certificate.uuid]', 33, 64, 18, 8, 11, '#7f1d1d', '600'),
      createText('mr-date', 'Date', '[certificate.issued_on]', 58, 64, 18, 8, 11, '#7f1d1d', '600'),
    ],
  },
  {
    id: 'digital-grid-portrait',
    name: 'Digital Grid',
    description: 'Portrait digital certificate with subtle panel grid.',
    category: 'digital',
    orientation: 'portrait',
    variables: ['[recipient.name]', '[certificate.issued_on]', '[certificate.uuid]'],
    elements: [
      createBoundary('system-boundary-dg2-p', '#1e3a8a', 2),
      {
        id: 'dg2-top-panel',
        type: 'shape',
        label: 'Top Panel',
        x: 2.5,
        y: 2.5,
        width: 95,
        height: 16,
        rotation: 0,
        zIndex: 1,
        visible: true,
        shapeType: 'rectangle',
        backgroundColor: '#1e3a8a',
        borderColor: '#1e3a8a',
        borderWidth: 0,
      },
      createText('dg2-title', 'Title', 'CERTIFICATE OF EXCELLENCE', 8, 6, 84, 8, 26, '#f8fafc', 'bold', 'center'),
      createText('dg2-sub', 'Subtitle', 'Presented to', 30, 30, 40, 4, 12, '#4b5563', '600', 'center'),
      createText('dg2-name', 'Name', '[recipient.name]', 16, 35, 68, 10, 32, '#1f2937', 'bold', 'center'),
      createText('dg2-body', 'Body', 'for successful completion of all learning modules.', 18, 50, 64, 8, 13, '#374151', '500', 'center'),
      createText('dg2-date', 'Date', '[certificate.issued_on]', 18, 90, 28, 4, 10, '#4b5563', '600'),
      createText('dg2-id', 'ID', '[certificate.uuid]', 54, 90, 28, 4, 10, '#4b5563', '600', 'right'),
    ],
  },
  {
    id: 'minimal-serif-portrait',
    name: 'Minimal Serif',
    description: 'Classic portrait style with serif-inspired spacing.',
    category: 'minimal',
    orientation: 'portrait',
    variables: ['[recipient.name]', '[certificate.issued_on]', '[certificate.uuid]'],
    elements: [
      createBoundary('system-boundary-ms-p', '#a3a3a3', 1),
      createText('ms-title', 'Title', 'Certificate', 24, 16, 52, 8, 36, '#374151', '600', 'center'),
      createText('ms-sub', 'Subtitle', 'of Achievement', 30, 24, 40, 6, 20, '#52525b', '500', 'center'),
      createText('ms-label', 'Label', 'This certifies that', 34, 40, 32, 4, 12, '#737373', '500', 'center'),
      createText('ms-name', 'Name', '[recipient.name]', 16, 45, 68, 9, 30, '#27272a', '600', 'center'),
      createText('ms-body', 'Body', 'has completed the professional training track.', 20, 58, 60, 7, 12, '#52525b', '500', 'center'),
      createText('ms-date-label', 'Date Label', 'Issued on', 24, 83, 20, 4, 10, '#737373', '500', 'center'),
      createText('ms-date', 'Date', '[certificate.issued_on]', 22, 88, 24, 4, 10, '#52525b', '600', 'center'),
      createText('ms-id-label', 'ID Label', 'Certificate Code', 56, 83, 24, 4, 10, '#737373', '500', 'center'),
      createText('ms-id', 'ID', '[certificate.uuid]', 54, 88, 28, 4, 10, '#52525b', '600', 'center'),
    ],
  },
  {
    id: 'modern-slate-landscape',
    name: 'Modern Slate',
    description: 'Landscape modern layout with slate accent stripe.',
    category: 'modern',
    orientation: 'landscape',
    variables: ['[recipient.name]', '[certificate.issued_on]', '[certificate.uuid]'],
    elements: [
      createBoundary('system-boundary-msl-l', '#334155', 2),
      {
        id: 'msl-stripe',
        type: 'shape',
        label: 'Accent Stripe',
        x: 2.5,
        y: 18,
        width: 95,
        height: 7,
        rotation: 0,
        zIndex: 1,
        visible: true,
        shapeType: 'rectangle',
        backgroundColor: '#334155',
        borderColor: '#334155',
        borderWidth: 0,
      },
      createText('msl-title', 'Title', 'CERTIFICATE OF ATTENDANCE', 8, 8, 70, 8, 26, '#1e293b', 'bold'),
      createText('msl-sub', 'Subtitle', 'Awarded to', 8, 31, 20, 4, 12, '#475569', '600'),
      createText('msl-name', 'Name', '[recipient.name]', 8, 37, 64, 10, 30, '#1e293b', '600'),
      createText('msl-body', 'Body', 'for active participation and completion of required sessions.', 8, 52, 64, 7, 13, '#475569', '500'),
      createText('msl-date', 'Date', '[certificate.issued_on]', 8, 89, 24, 4, 10, '#475569', '600'),
      createText('msl-id', 'ID', '[certificate.uuid]', 68, 89, 24, 4, 10, '#475569', '600', 'right'),
    ],
  },
];
